UPDATE materiales SET año_publicacion = 1963 WHERE titulo = 'La ciudad y los perros';
UPDATE materiales SET año_publicacion = 1872 WHERE titulo = 'Tradiciones Peruanas';
UPDATE materiales SET año_publicacion = 1971 WHERE titulo = 'El zorro de arriba y el zorro de abajo';
UPDATE materiales SET año_publicacion = 1958 WHERE titulo = 'Los ríos profundos';
UPDATE materiales SET año_publicacion = 1974 WHERE titulo = 'La palabra del mudo';
UPDATE materiales SET año_publicacion = 1970 WHERE titulo = 'Un mundo para Julius';
UPDATE materiales SET año_publicacion = 1928 WHERE titulo = 'La casa de cartón';
UPDATE materiales SET año_publicacion = 1995 WHERE titulo = 'No me esperen en abril';
UPDATE materiales SET año_publicacion = 1957 WHERE titulo = 'El pez de oro';
UPDATE materiales SET año_publicacion = 1962 WHERE titulo = 'La agonía de Rasu Ñiti';
UPDATE materiales SET año_publicacion = 1999 WHERE titulo = 'Revista de Investigaciones Altoandinas';
UPDATE materiales SET año_publicacion = 1983 WHERE titulo = 'Revista Andina';
UPDATE materiales SET año_publicacion = 1981 WHERE titulo = 'Revista del Archivo General de la Nación';
UPDATE materiales SET año_publicacion = 1944 WHERE titulo = 'Revista de Derecho PUCP';
UPDATE materiales SET año_publicacion = 2017 WHERE titulo = 'Revista Kawsaypacha';
UPDATE materiales SET año_publicacion = 1974 WHERE titulo = 'Apuntes';
UPDATE materiales SET año_publicacion = 1990 WHERE titulo = 'Debate Agrario';
UPDATE materiales SET año_publicacion = 1942 WHERE titulo = 'Revista Peruana de Medicina Experimental y tituloSalud Pública';
UPDATE materiales SET año_publicacion = 1918 WHERE titulo = 'Anales de la Facultad de Medicina';
UPDATE materiales SET año_publicacion = 1996 WHERE titulo = 'Revista del Instituto Riva-Agüero';
UPDATE materiales SET año_publicacion = 2001 WHERE titulo = 'Actas del Congreso Nacional de Historia';
UPDATE materiales SET año_publicacion = 1999 WHERE titulo = 'Actas del Congreso de Literatura Peruana';
UPDATE materiales SET año_publicacion = 2005 WHERE titulo = 'Actas del Congreso de Estudiantes de Medicina';
UPDATE materiales SET año_publicacion = 2008 WHERE titulo = 'Memorias del Congreso de Ciencias Sociales';
UPDATE materiales SET año_publicacion = 2010 WHERE titulo = 'Actas del Congreso de Ingeniería Civil';
UPDATE materiales SET año_publicacion = 2015 WHERE titulo = 'Memorias del Congreso de Educación Intercultural';
UPDATE materiales SET año_publicacion = 2003 WHERE titulo = 'Actas del Simposio de Arqueología Andina';
UPDATE materiales SET año_publicacion = 2006 WHERE titulo = 'Congreso Internacional de Historia Regional';
UPDATE materiales SET año_publicacion = 2011 WHERE titulo = 'Actas del Congreso de Bibliotecología';
UPDATE materiales SET año_publicacion = 2012 WHERE titulo = 'Memorias del Encuentro Nacional de Archivos';
UPDATE materiales SET año_publicacion = 1942 WHERE titulo = 'Revista Peruana de Medicina Experimental y Salud Pública';
